Fixed Zod Validation #13
uninbox/UnInbox pull request #14
Opened 2024-01-15 18:49 UTC by skushagra9

Added the trim() function to zod validation

2024-01-15 20:49 UTC, McPizza0 requested changes
The order of operations matters with zod
z.string.min(1).max(3).trim() will return valid for a string of `' '`
the trim needs to come first, so all other rules are checked on the trimmed string

z.trim().min(1).max(5) will fail with a string of `' '`

can you please update all the schemas to reflect this

2024-01-15 20:49 UTC, McPizza0 commented on apps/web-app/pages/[orgSlug]/settings/user/profiles.vue
schema validation didnt exist here before
maybe we can just set it to z.string().trim() without a min/max

2024-01-15 20:49 UTC, McPizza0 commented on apps/web-app/pages/join/org.vue
> +              .trim()
Same here, regex already covers, can remove .trim

2024-01-15 20:49 UTC, McPizza0 commented on apps/web-app/pages/join/index.vue
> +            .trim()
the regex here already covers spaces, we can remove .trim

2024-01-15 20:49 UTC, McPizza0 commented on apps/web-app/pages/join/profile.vue
> +            :schema="z.string().min(1).max(32).trim()"
schema validation didnt exist here before
maybe we can just set it to z.string().trim() without a min/max

2024-01-15 20:49 UTC, McPizza0 commented on apps/web-app/pages/join/profile.vue
> +            :schema="z.string().min(1).max(32).trim()"
schema validation didnt exist here before
maybe we can just set it to z.string().trim() without a min/max

2024-01-16 03:52 UTC, skushagra9 commented
@McPizza0 Sure, I will make the changes

2024-01-16 10:03 UTC, McPizza0 approved these changes
lgtm

2024-01-16 10:05 UTC, merged

2024-03-28 12:34 UTC, McPizza0 commented
hey @skushagra9 

we have been strongly advised to add a contributor license agreement
motivation is to ensure that your contributions can only be "commercialized" or offered as a saas by the UnInbox team (Unproprietary Corporation) and not by others
please head over to https://cla-assistant.io/un/inbox and sign the agreement 
once we have more funds for legal stuff, we'll get a custom one built to add in clauses to the effect of "no changing to non-open licenses" etc.

thank you

2024-03-28 13:33 UTC, skushagra9 commented
sure, thanks