Added profile refresh
uninbox/UnInbox pull request #51
Opened 2024-02-03 09:37 UTC by skushagra9

## What does this PR do?

Fixes #43 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### Required
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

2024-02-03 09:43 UTC, McPizza0 requested changes
you rushed into solving this
the primary issue is not resolved
please run the app locally and go through the user flow to understand the issue

2024-02-03 09:43 UTC, McPizza0 commented on apps/web-app/pages/[orgSlug]/settings/org/index.vue
> +    refreshNuxtData('getUserSingleProfileNav');
why is this here?
we only need to refresh the org profile since thats what we are changing

2024-02-03 09:43 UTC, McPizza0 commented on apps/web-app/pages/[orgSlug]/settings/user/profiles.vue
> +    refreshNuxtData('getUserOrgsNav');
why is this here?
we only need to refresh the user profile since thats what we are changing

2024-02-03 09:43 UTC, McPizza0 commented on apps/web-app/pages/join/profile.vue
> +    refreshNuxtData('getUserOrgsNav');
why are these here?
the data for them only loads when the user is in the app

2024-02-03 09:44 UTC, skushagra9 commented
ok , I will resolve it

2024-02-04 09:03 UTC, skushagra9 commented
I tested these changes in the feat/attatchment-upload branch and there its working fine but the the avatar on the page doesn't changes

2024-02-04 16:04 UTC, skushagra9 commented
I have added nuxtrefresh before the uploading.value = false to enhance userExperience

2024-02-04 16:24 UTC, skushagra9 commented
its failing with usefetch on another branch, adding $fetch

2024-02-05 10:19 UTC, McPizza0 requested changes

2024-02-05 10:19 UTC, McPizza0 commented on apps/web-app/pages/join/profile.vue
> -
we should also do the same thing here, after upload set the image url to the returned avatarId

2024-02-05 10:39 UTC, McPizza0 approved these changes

2024-02-05 10:39 UTC, merged